# Site settings
title: DOB Dispatch User Guide
author: EastBanc Technologies
name: EastBanc Technologies
description: "DOB App User Manual | eastbanctech.com"
email: contact@eastbanctech.com
webpage: https://eastbanctech.com/

plugins:
  - jekyll-remote-theme
  - "jekyll-seo-tag"


#google analytics
ga_tracking: G-0405LGTJTB
ga_tracking_anonymize_ip: true


# Build settings
remote_theme: pmarsceill/just-the-docs

color_scheme: foo

# Aux links for the upper right navigation
aux_links:
  "DOB":
    - "https://dcratransition.dc.gov/dob/"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

search_enabled: true
search:
  previews: 2
  preview_words_before: 2
  preview_words_after: 5
  # Display the relative url in search results
  rel_url: false
